version: '3.8'

services:
  order_service: 
    hostname: order_service
    build: 
      context: ./
      target: build
    command: ["go", "run", "/build/cmd/app/main.go"]
    ports:
      - 9999:9999