version: '3'

# Task is a make-like script manager written in go. https://taskfile.dev/usage/

tasks:
  run:
    summary: |
      Run the application with live-reloading using air.
      Installs air if it is not already installed
    cmds:
      - |
        if ! [ -x "$(command -v air)" ]; then
          echo "Air is not installed. Installing"
          go install github.com/cosmtrek/air@latest
        fi
      - air

  post:
    summary: |
      POST an order to the order service
      Usage: task post -- <product name>
    cmds:
      - |
        curl --request POST \
          --silent \
          --url http://localhost:9999/orders \
          --header 'Content-Type: application/json' \
          --data "{
          \"Product\": \"{{.CLI_ARGS}}\",
          \"Quantity\": 1
        }" | jq
  get:
    summary: |
      Get all orders in the service
      Usage: task get
    cmds:
      - |
        curl --request GET \
        --silent \
        --url http://localhost:9999/orders \
        --header 'Content-Type: application/json' | jq

  up:
    summary: |
      Run the application using a local docker-compose environment
    cmds:
      - docker-compose up --build -d 
      - docker-compose logs -f

  down:
    summary: |
      Tear-down the docker-compose environmnet
    cmds:
      - docker-compose down
